language: objective-c
before_install:
    - git submodule init && git submodule update
    - brew update
    - brew install xctool --HEAD
    - cd Tests && pod install && cd $TRAVIS_BUILD_DIR
script: rake test